version: '3.8'

services:
  # PostgreSQL database with pgvector
  db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: sekai_memory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/ddl.sql:/docker-entrypoint-initdb.d/01-ddl.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Sekai Memory System API
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/sekai_memory
      LOG_LEVEL: INFO
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./eval/results:/app/eval/results
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: